apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: circuitbreaker-reviews-v1
spec:
  destination:
    namespace: bookinfo
    name: reviews
    labels:
      version: v1
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      httpMaxPendingRequests: 1
      sleepWindow: 2m
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100
      httpConsecutiveErrors: 1
      httpMaxRequestsPerConnection: 1
