apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-v1-v2
spec:
  destination:
    namespace: bookinfo
    name: reviews
  precedence: 5
  route:
  - labels:
      version: v1
    weight: 90
  - labels:
      version: v2
    weight: 10
